//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#00  7.4KW_CCU_L.
        /// </summary>
        internal static string CH00 {
            get {
                return ResourceManager.GetString("CH00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#01  ELECTRONIC:3000W.
        /// </summary>
        internal static string CH01 {
            get {
                return ResourceManager.GetString("CH01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#02  COOLANT AREA:3000W.
        /// </summary>
        internal static string CH02 {
            get {
                return ResourceManager.GetString("CH02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#03  ELECTRONIC:7.4KW.
        /// </summary>
        internal static string CH03 {
            get {
                return ResourceManager.GetString("CH03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#04  COOLANT AREA:7.4KW.
        /// </summary>
        internal static string CH04 {
            get {
                return ResourceManager.GetString("CH04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#05  5DH_COOL.
        /// </summary>
        internal static string CH05 {
            get {
                return ResourceManager.GetString("CH05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#06  5DH_ELEC.
        /// </summary>
        internal static string CH06 {
            get {
                return ResourceManager.GetString("CH06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#07  PAG_PV.
        /// </summary>
        internal static string CH07 {
            get {
                return ResourceManager.GetString("CH07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#08  AUDI_PV.
        /// </summary>
        internal static string CH08 {
            get {
                return ResourceManager.GetString("CH08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#09  GEN2_ELEC.
        /// </summary>
        internal static string CH09 {
            get {
                return ResourceManager.GetString("CH09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#10  GEN2_COOL.
        /// </summary>
        internal static string CH10 {
            get {
                return ResourceManager.GetString("CH10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#11  GEN2_COOL_H74.
        /// </summary>
        internal static string CH11 {
            get {
                return ResourceManager.GetString("CH11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#12 BMW CCU-L.
        /// </summary>
        internal static string CH12 {
            get {
                return ResourceManager.GetString("CH12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#13  BMW CCU-S.
        /// </summary>
        internal static string CH13 {
            get {
                return ResourceManager.GetString("CH13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#14  REF.PL57/65.
        /// </summary>
        internal static string CH14 {
            get {
                return ResourceManager.GetString("CH14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#15  REF.PL73/1P.
        /// </summary>
        internal static string CH15 {
            get {
                return ResourceManager.GetString("CH15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#16  PL73-1P_K_11.
        /// </summary>
        internal static string CH16 {
            get {
                return ResourceManager.GetString("CH16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#17  PL57/95_K_11.
        /// </summary>
        internal static string CH17 {
            get {
                return ResourceManager.GetString("CH17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#18  PL73-1P_DES.
        /// </summary>
        internal static string CH18 {
            get {
                return ResourceManager.GetString("CH18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#19  PL57/65_DES.
        /// </summary>
        internal static string CH19 {
            get {
                return ResourceManager.GetString("CH19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#20  PL73-1P_DES2.
        /// </summary>
        internal static string CH20 {
            get {
                return ResourceManager.GetString("CH20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#21  PL57/65_DES2.
        /// </summary>
        internal static string CH21 {
            get {
                return ResourceManager.GetString("CH21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#22  NEW.PL57/65.
        /// </summary>
        internal static string CH22 {
            get {
                return ResourceManager.GetString("CH22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#23  NEW.PL73-1P.
        /// </summary>
        internal static string CH23 {
            get {
                return ResourceManager.GetString("CH23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#24  PV2017 PL57/65.
        /// </summary>
        internal static string CH24 {
            get {
                return ResourceManager.GetString("CH24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#25  PV2017 PL73-1P PAG.
        /// </summary>
        internal static string CH25 {
            get {
                return ResourceManager.GetString("CH25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#26  PV2017 PL57/65 NON.
        /// </summary>
        internal static string CH26 {
            get {
                return ResourceManager.GetString("CH26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#27  PV2017 PL73-1P NON.
        /// </summary>
        internal static string CH27 {
            get {
                return ResourceManager.GetString("CH27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#28  GEN4_11KW_ELEC.
        /// </summary>
        internal static string CH28 {
            get {
                return ResourceManager.GetString("CH28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#29  GEN4_11KW_COOLING.
        /// </summary>
        internal static string CH29 {
            get {
                return ResourceManager.GetString("CH29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#30  GEN4_3.7KW_ELEC.
        /// </summary>
        internal static string CH30 {
            get {
                return ResourceManager.GetString("CH30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH#31  GEN4_3.7KW_COOLING.
        /// </summary>
        internal static string CH31 {
            get {
                return ResourceManager.GetString("CH31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        internal static string Code0000 {
            get {
                return ResourceManager.GetString("Code0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 1 PS Offset Error.
        /// </summary>
        internal static string Code0020 {
            get {
                return ResourceManager.GetString("Code0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 3 Test Pressure Error.
        /// </summary>
        internal static string Code0080 {
            get {
                return ResourceManager.GetString("Code0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Leak.
        /// </summary>
        internal static string Code0100 {
            get {
                return ResourceManager.GetString("Code0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 2 PS Output Out of Range.
        /// </summary>
        internal static string Code0200 {
            get {
                return ResourceManager.GetString("Code0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 24 K(Ve) Value Out of Range.
        /// </summary>
        internal static string Code0400 {
            get {
                return ResourceManager.GetString("Code0400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K(Ve) Check NG.
        /// </summary>
        internal static string Code0800 {
            get {
                return ResourceManager.GetString("Code0800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: 11 to 16 Air Operated Value Error.
        /// </summary>
        internal static string Code4000 {
            get {
                return ResourceManager.GetString("Code4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delta {
            get {
                object obj = ResourceManager.GetObject("delta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_fail {
            get {
                object obj = ResourceManager.GetObject("gui_fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_failv2 {
            get {
                object obj = ResourceManager.GetObject("gui_failv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_normal {
            get {
                object obj = ResourceManager.GetObject("gui_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_normalv2 {
            get {
                object obj = ResourceManager.GetObject("gui_normalv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_pass {
            get {
                object obj = ResourceManager.GetObject("gui_pass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui_passv2 {
            get {
                object obj = ResourceManager.GetObject("gui_passv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_about_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_about_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_checkmark_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_checkmark_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_close_window_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_close_window_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_close_window_dark_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_close_window_dark_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_conflict_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_conflict_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_conflict_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_conflict_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_connected_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_connected_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_delete_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_delete_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_disconnected_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_disconnected_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_full_stop_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_full_stop_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_internet_of_things_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_internet_of_things_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_open_folder_in_new_tab_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_open_folder_in_new_tab_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_project_management_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_project_management_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_project_management_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_project_management_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_question_mark_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_question_mark_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_screenshot_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_screenshot_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_shutdown_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_shutdown_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_tick_box_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_tick_box_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_tick_box_dark_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_tick_box_dark_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_timetable_64 {
            get {
                object obj = ResourceManager.GetObject("icons8_timetable_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leak {
            get {
                object obj = ResourceManager.GetObject("leak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak test.
        /// </summary>
        internal static string Mode00 {
            get {
                return ResourceManager.GetString("Mode00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastering.
        /// </summary>
        internal static string Mode01 {
            get {
                return ResourceManager.GetString("Mode01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K(Ve) check.
        /// </summary>
        internal static string Mode02 {
            get {
                return ResourceManager.GetString("Mode02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string Mode03 {
            get {
                return ResourceManager.GetString("Mode03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pe1 {
            get {
                object obj = ResourceManager.GetObject("pe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LL FAIL.
        /// </summary>
        internal static string Result1 {
            get {
                return ResourceManager.GetString("Result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        internal static string Result2 {
            get {
                return ResourceManager.GetString("Result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UL FAIL.
        /// </summary>
        internal static string Result4 {
            get {
                return ResourceManager.GetString("Result4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LL2 FAIL.
        /// </summary>
        internal static string Result9 {
            get {
                return ResourceManager.GetString("Result9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UL2 FAIL.
        /// </summary>
        internal static string ResultC {
            get {
                return ResourceManager.GetString("ResultC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ResultD {
            get {
                return ResourceManager.GetString("ResultD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unitag_QRCode_1633566970790 {
            get {
                object obj = ResourceManager.GetObject("Unitag_QRCode_1633566970790", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unitag_QRCode_1633567236824 {
            get {
                object obj = ResourceManager.GetObject("Unitag_QRCode_1633567236824", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unitag_QRCode_1633567566589 {
            get {
                object obj = ResourceManager.GetObject("Unitag_QRCode_1633567566589", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
